// This file is generated by GoAdmin CLI adm.
package bus

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "first_dd_detail" => http://localhost:9033/admin/info/first_dd_detail
// "first_users" => http://localhost:9033/admin/info/first_users
//
// example end
var Generators = map[string]table.Generator{

	"first_dd_detail": GetFirstdddetailTable,
	"first_users":     GetFirstusersTable,

	// generators end
}
